package g_mungus.alpha_omega.nether;

import g_mungus.alpha_omega.mixin.server.ChunkMapAccessor;
import g_mungus.alpha_omega.neighbour.ImageGeometry;
import g_mungus.alpha_omega.orbifold.Orbifold;
import g_mungus.alpha_omega.worldgen.OrbifoldChunkGenerator;
import net.minecraft.network.protocol.game.ClientboundSetChunkCacheRadiusPacket;
import net.minecraft.resources.ResourceKey;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.chunk.ChunkGenerator;

/**
 * The view distance of an orbifold level is limited to {@link ImageGeometry#maxViewDistance}: only a small Nether, whose
 * tile a full view would cross many times (the small size's Nether tile is 12 chunks tall; 25 images at 32 chunks), is
 * limited at all. The level's chunk map takes the limit ({@code ChunkMapViewMixin}). Vanilla tells clients the server's
 * view distance only when they join or it changes, so each player is told the distance of the level it is in whenever
 * that can differ: on joining, changing dimension or respawning, and after the server's distance changes
 * ({@code PlayerListViewMixin}). That also bounds the images its client draws.
 */
public final class NetherView {

    private NetherView() {
    }

    /** The largest view distance for a level of {@code dimension} generated by {@code generator}: 32 unless it is a small orbifold. */
    public static int maxViewDistance(ResourceKey<Level> dimension, ChunkGenerator generator) {
        if (!Orbifold.mayBeOrbifold(dimension) || !(generator instanceof OrbifoldChunkGenerator orbifold)) return 32;
        return ImageGeometry.maxViewDistance(orbifold.geometry());
    }

    /** The view distance a level sends with. */
    public static int viewDistance(ServerLevel level) {
        return ((ChunkMapAccessor) level.getChunkSource().chunkMap).alpha_omega$serverViewDistance();
    }

    /** Tells a player the view distance of the level it is in. */
    public static void sync(ServerPlayer player) {
        player.connection.send(new ClientboundSetChunkCacheRadiusPacket(viewDistance(player.serverLevel())));
    }

    /** After the server's view distance changed (sent to everyone): players in a limited level are told their own. */
    public static void syncLimited(MinecraftServer server) {
        int view = server.getPlayerList().getViewDistance();
        for (ServerPlayer player : server.getPlayerList().getPlayers()) {
            if (viewDistance(player.serverLevel()) != view) sync(player);
        }
    }
}
