package g_mungus.alpha_omega.worldgen;

import com.mojang.serialization.MapCodec;
import com.mojang.serialization.codecs.RecordCodecBuilder;
import g_mungus.alpha_omega.AlphaOmegaMod;
import g_mungus.alpha_omega.config.AlphaOmegaConfig;
import g_mungus.alpha_omega.orbifold.OrbifoldGeometry;
import g_mungus.alpha_omega.orbifold.OrbifoldSettings;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.atomic.AtomicInteger;
import net.minecraft.core.Holder;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.level.WorldGenRegion;
import net.minecraft.world.level.ChunkPos;
import net.minecraft.world.level.StructureManager;
import net.minecraft.world.level.WorldGenLevel;
import net.minecraft.world.level.biome.BiomeManager;
import net.minecraft.world.level.biome.BiomeSource;
import net.minecraft.world.level.chunk.ChunkAccess;
import net.minecraft.world.level.chunk.ChunkGenerator;
import net.minecraft.world.level.levelgen.GenerationStep;
import net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator;
import net.minecraft.world.level.levelgen.NoiseGeneratorSettings;
import net.minecraft.world.level.levelgen.RandomState;
import net.minecraft.world.level.levelgen.blending.Blender;
import net.minecraft.world.level.levelgen.presets.WorldPreset;
import net.minecraft.world.level.levelgen.structure.BoundingBox;

/**
 * The overworld generator of an orbifold world. Its settings are the orbifold's shape, so a world is an orbifold world
 * exactly when its overworld uses this generator.
 *
 * <p>Each chunk is generated by its {@link Region} ({@code orbifold-implementation.md} phase 3, {@code rotated-seams.md}
 * §6.1):
 * <ul>
 * <li>{@link Region#TILE}: vanilla terrain, surface, carvers, features, structures and mobs.</li>
 * <li>{@link Region#BAND} and {@link Region#SKIRT}: empty. Every step is skipped, so the chunk is air, its heightmaps
 * sit at the bottom of the world and the sky lights it fully. Phase 4 fills it from its source ({@link #awaitsFill}).</li>
 * <li>{@link Region#VOID}, outside the footprint: empty, and never needed.</li>
 * </ul>
 *
 * <p>Generation never writes outside the tile: features and structure pieces of a tile chunk that reach past a seam are
 * cut there (the write guard, {@code WorldGenRegionMixin}), and a structure is only kept when its whole box is inside
 * the tile, {@link #STRUCTURE_MARGIN} clear of every seam ({@code ChunkGeneratorMixin}). Carvers write into the chunk
 * they carve, which is only ever a tile chunk.
 */
public class OrbifoldChunkGenerator extends NoiseBasedChunkGenerator {

    public static final ResourceKey<WorldPreset> PRESET =
        ResourceKey.create(Registries.WORLD_PRESET, ResourceLocation.fromNamespaceAndPath(AlphaOmegaMod.MOD_ID, "orbifold"));

    public static final MapCodec<OrbifoldChunkGenerator> CODEC = RecordCodecBuilder.mapCodec(instance -> instance.group(
        BiomeSource.CODEC.fieldOf("biome_source").forGetter(ChunkGenerator::getBiomeSource),
        NoiseGeneratorSettings.CODEC.fieldOf("settings").forGetter(NoiseBasedChunkGenerator::generatorSettings),
        OrbifoldSettings.fieldsCodec(AlphaOmegaConfig::defaults).forGetter(OrbifoldChunkGenerator::orbifold)
    ).apply(instance, OrbifoldChunkGenerator::new));

    /** Structures keep this many blocks clear of every seam. */
    public static final int STRUCTURE_MARGIN = 8;

    /** Structure starts turned away for reaching past the tile, for tests and debugging. */
    public static final AtomicInteger REJECTED_STRUCTURES = new AtomicInteger();

    /** What a chunk is to the generator. Every footprint boundary is a multiple of 16, so a chunk is wholly one. */
    public enum Region {
        /** Inside the tile: generated as vanilla terrain. */
        TILE,
        /** In the band past a seam: generated empty, then filled from its source. */
        BAND,
        /** In the skirt past the band: generated empty, then filled from its source. */
        SKIRT,
        /** Outside the footprint: generated empty and left so. */
        VOID
    }

    private final OrbifoldSettings orbifold;
    private final OrbifoldGeometry geometry;

    public OrbifoldChunkGenerator(BiomeSource biomeSource, Holder<NoiseGeneratorSettings> settings, OrbifoldSettings orbifold) {
        super(biomeSource, settings);
        this.orbifold = orbifold;
        this.geometry = orbifold.geometry();
    }

    public OrbifoldSettings orbifold() {
        return this.orbifold;
    }

    public OrbifoldGeometry geometry() {
        return this.geometry;
    }

    // ---- Regions ----

    public Region region(int chunkX, int chunkZ) {
        if (this.geometry.isTileChunk(chunkX, chunkZ)) return Region.TILE;
        if (this.geometry.isBandChunk(chunkX, chunkZ)) return Region.BAND;
        if (this.geometry.isSkirtChunk(chunkX, chunkZ)) return Region.SKIRT;
        return Region.VOID;
    }

    public Region region(ChunkPos pos) {
        return this.region(pos.x, pos.z);
    }

    /** Whether the generator makes this chunk's terrain: only tile chunks. */
    public boolean generates(ChunkPos pos) {
        return this.geometry.isTileChunk(pos.x, pos.z);
    }

    /**
     * The hook for phase 4: whether generation leaves this chunk empty for a copy of its source to fill. True for band
     * and skirt chunks, whose source is {@link OrbifoldGeometry#canonChunk}; false for tile chunks (generated) and void
     * ones (never filled). Whether a given chunk <i>has</i> been filled is phase 4's to track.
     */
    public boolean awaitsFill(ChunkPos pos) {
        Region region = this.region(pos);
        return region == Region.BAND || region == Region.SKIRT;
    }

    // ---- Structures ----

    /** Whether a structure with this bounding box may generate: wholly inside the tile, {@link #STRUCTURE_MARGIN} clear of every seam. */
    public boolean fitsInTile(BoundingBox box) {
        OrbifoldGeometry g = this.geometry;
        return box.minX() >= g.minX + STRUCTURE_MARGIN && box.maxX() < g.maxX - STRUCTURE_MARGIN
            && box.minZ() >= g.northRow + STRUCTURE_MARGIN && box.maxZ() < g.southRow - STRUCTURE_MARGIN;
    }

    /** {@link #fitsInTile}, counting rejections: called as each structure start is generated. */
    public boolean keepStructure(BoundingBox box) {
        boolean fits = this.fitsInTile(box);
        if (!fits) {
            REJECTED_STRUCTURES.incrementAndGet();
            AlphaOmegaMod.LOGGER.debug("Structure at {} reaches past the tile", box);
        }
        return fits;
    }

    // ---- Writes ----

    /** Whether generation may write a block: only inside the tile (the write guard, {@code rotated-seams.md} §6.4 version 1). */
    public boolean mayWrite(int x, int z) {
        return this.geometry.isTile(x, z);
    }

    // ---- Steps: tile chunks only ----

    @Override
    public CompletableFuture<ChunkAccess> fillFromNoise(Blender blender, RandomState random, StructureManager structures, ChunkAccess chunk) {
        if (!this.generates(chunk.getPos())) return CompletableFuture.completedFuture(chunk);
        return super.fillFromNoise(blender, random, structures, chunk);
    }

    /**
     * Vanilla's noise fill for any chunk, whatever its region: for measuring what a band chunk would hold if it were
     * generated, against the source it is filled from ({@code TerrainGameTests}).
     */
    public CompletableFuture<ChunkAccess> fillAnyFromNoise(Blender blender, RandomState random, StructureManager structures, ChunkAccess chunk) {
        return super.fillFromNoise(blender, random, structures, chunk);
    }

    @Override
    public void buildSurface(WorldGenRegion region, StructureManager structures, RandomState random, ChunkAccess chunk) {
        if (this.generates(chunk.getPos())) super.buildSurface(region, structures, random, chunk);
    }

    @Override
    public void applyCarvers(WorldGenRegion region, long seed, RandomState random, BiomeManager biomes, StructureManager structures,
                             ChunkAccess chunk, GenerationStep.Carving step) {
        if (this.generates(chunk.getPos())) super.applyCarvers(region, seed, random, biomes, structures, chunk, step);
    }

    @Override
    public void applyBiomeDecoration(WorldGenLevel level, ChunkAccess chunk, StructureManager structures) {
        if (this.generates(chunk.getPos())) super.applyBiomeDecoration(level, chunk, structures);
    }

    @Override
    public void spawnOriginalMobs(WorldGenRegion region) {
        if (this.generates(region.getCenter())) super.spawnOriginalMobs(region);
    }

    @Override
    protected MapCodec<? extends ChunkGenerator> codec() {
        return CODEC;
    }
}
